2024-02-20 13:48:22,930 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 13:48:22,969 ERROR __main__ Thread-4 (process_request_thread) : Error closing RabbitMQ connection: BlockingConnection.close(200, 'Normal shutdown') called on closed connection.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 126, in teardown_rabbitmq
    connection.close()
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 800, in close
    raise exceptions.ConnectionWrongStateError(msg)
pika.exceptions.ConnectionWrongStateError: BlockingConnection.close(200, 'Normal shutdown') called on closed connection.
2024-02-20 13:49:14,508 WARNING __main__ Thread-5 (process_request_thread) : No  MSFT news data found.
2024-02-20 13:49:14,509 ERROR __main__ Thread-5 (process_request_thread) : Error closing RabbitMQ connection: BlockingConnection.close(200, 'Normal shutdown') called on closed connection.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 126, in teardown_rabbitmq
    connection.close()
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 800, in close
    raise exceptions.ConnectionWrongStateError(msg)
pika.exceptions.ConnectionWrongStateError: BlockingConnection.close(200, 'Normal shutdown') called on closed connection.
2024-02-20 13:50:40,428 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 13:50:52,627 WARNING __main__ Thread-4 (process_request_thread) : No  MSFT news data found.
2024-02-20 13:51:01,922 WARNING __main__ Thread-5 (process_request_thread) : No Cummins news data found.
2024-02-20 14:04:38,742 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:04:42,986 ERROR __main__ Thread-5 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 142, in user
    channel.basic_publish(exchange='',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 14:15:10,561 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:15:13,810 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: cannot access local variable 'channel' where it is not associated with a value
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 140, in user
    if not channel or channel.is_closed:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'channel' where it is not associated with a value
2024-02-20 14:34:16,520 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:34:20,157 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 14:37:21,016 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:37:24,441 INFO __main__ Thread-5 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 14:37:24,453 ERROR __main__ Thread-5 (process_request_thread) : An error occurred: 'index' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 155, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 30, in top-level template code
    <td>{{ index + 1 }}</td>
jinja2.exceptions.UndefinedError: 'index' is undefined
2024-02-20 14:43:15,114 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 14:43:15,118 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: 'index' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 156, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 30, in top-level template code
    <td>{{ index + 1 }}</td>
jinja2.exceptions.UndefinedError: 'index' is undefined
2024-02-20 14:43:15,127 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:46:19,718 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: cannot access local variable 'channel' where it is not associated with a value
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 151, in user
    if not channel or channel.is_closed:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'channel' where it is not associated with a value
2024-02-20 14:46:19,775 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:51:10,996 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: cannot access local variable 'channel' where it is not associated with a value
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 151, in user
    if not channel or channel.is_closed:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'channel' where it is not associated with a value
2024-02-20 14:51:11,046 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 14:53:18,180 INFO __main__ Thread-2 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 14:53:18,185 ERROR __main__ Thread-2 (process_request_thread) : An error occurred: 'index' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 153, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 30, in top-level template code
    <td>{{ index + 1 }}</td>
jinja2.exceptions.UndefinedError: 'index' is undefined
2024-02-20 14:53:18,191 ERROR __main__ Thread-2 (process_request_thread) : Error closing RabbitMQ connection: name 'connection' is not defined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 133, in teardown_rabbitmq
    if connection and connection.is_open:
       ^^^^^^^^^^
NameError: name 'connection' is not defined
2024-02-20 14:57:09,458 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 14:57:09,461 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: 'index' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 156, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 30, in top-level template code
    <td>{{ index + 1 }}</td>
jinja2.exceptions.UndefinedError: 'index' is undefined
2024-02-20 14:57:09,507 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:01:03,558 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: object of type 'Response' has no len()
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 153, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=jsonify(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 427, in basic_publish
    self._send_method(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1415, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2253, in _send_method
    self._send_message(channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2266, in _send_message
    length = len(content[1])
             ^^^^^^^^^^^^^^^
TypeError: object of type 'Response' has no len()
2024-02-20 15:01:03,568 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:02:03,015 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: cannot access local variable 'channel' where it is not associated with a value
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    if not channel or channel.is_closed:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'channel' where it is not associated with a value
2024-02-20 15:02:03,021 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:02:34,551 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: object of type 'Response' has no len()
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 154, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=jsonify(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 427, in basic_publish
    self._send_method(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1415, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2253, in _send_method
    self._send_message(channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2266, in _send_message
    length = len(content[1])
             ^^^^^^^^^^^^^^^
TypeError: object of type 'Response' has no len()
2024-02-20 15:02:34,559 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:06:27,959 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:06:27,964 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: 'index' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 160, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 30, in top-level template code
    <td>{{ index + 1 }}</td>
jinja2.exceptions.UndefinedError: 'index' is undefined
2024-02-20 15:06:27,973 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:10:06,119 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:10:06,130 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 157, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 35, in template
    <td>{{ item.published_date }}</td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2024-02-20 15:10:06,143 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:11:14,122 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:11:16,758 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:11:16,761 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 157, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 35, in template
    <td>{{ item.published_date }}</td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2024-02-20 15:12:39,903 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:12:44,878 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:12:44,890 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: 'list object' has no attribute 'items'
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 157, in user
    return render_template('user.html',items=news_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 29, in top-level template code
    {% for index, item in items.items() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
2024-02-20 15:16:01,397 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: object of type 'Response' has no len()
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 156, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=body)
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 427, in basic_publish
    self._send_method(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1415, in _send_method
    self.connection._send_method(self.channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2253, in _send_method
    self._send_message(channel_number, method, content)
  File "C:\Python\Lib\site-packages\pika\connection.py", line 2266, in _send_message
    length = len(content[1])
             ^^^^^^^^^^^^^^^
TypeError: object of type 'Response' has no len()
2024-02-20 15:16:01,405 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:18:42,965 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:18:42,972 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:22:52,175 INFO __main__ Thread-3 (process_request_thread) :  MSFT news data published to RabbitMQ.
2024-02-20 15:22:52,181 ERROR __main__ Thread-3 (process_request_thread) : An error occurred: 'items' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 160, in user
    return render_template('user.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 29, in top-level template code
    {% for index, item in items.items() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'items' is undefined
2024-02-20 15:22:52,191 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:22:55,653 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:22:55,654 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: 'items' is undefined
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 160, in user
    return render_template('user.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\CSA\competitor-news\attempt\templates\user.html", line 29, in top-level template code
    {% for index, item in items.items() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'items' is undefined
2024-02-20 15:26:11,123 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:26:11,131 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:28:52,028 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:28:52,088 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:29:04,932 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 155, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:29:24,420 ERROR __main__ Thread-5 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 155, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:29:47,873 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:29:47,880 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:29:50,293 INFO __main__ Thread-4 (process_request_thread) : 123 news data published to RabbitMQ.
2024-02-20 15:29:56,253 INFO __main__ Thread-6 (process_request_thread) :  MSFT news data published to RabbitMQ.
2024-02-20 15:30:08,203 INFO __main__ Thread-8 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 15:34:24,001 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:34:24,046 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:34:39,266 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 153, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:35:37,255 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:35:46,708 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 153, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:36:16,021 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:36:19,179 INFO __main__ Thread-4 (process_request_thread) :  MSFT news data published to RabbitMQ.
2024-02-20 15:36:22,797 INFO __main__ Thread-5 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 15:39:31,228 ERROR __main__ Thread-7 (process_request_thread) : An error occurred: Stream connection lost: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 153, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2265, in basic_publish
    self._flush_output()
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 1353, in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.StreamLostError: Stream connection lost: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)
2024-02-20 15:40:23,061 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:40:27,561 INFO __main__ Thread-5 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 15:40:51,596 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:40:51,646 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:40:54,397 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:42:21,309 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:42:24,445 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:44:20,729 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:44:20,783 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:44:44,808 INFO __main__ Thread-4 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 15:45:03,098 INFO __main__ Thread-6 (process_request_thread) : AAPL news data published to RabbitMQ.
2024-02-20 15:47:39,663 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:47:39,714 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:47:42,669 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 143, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:51:29,390 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:53:38,569 ERROR __main__ Thread-4 (process_request_thread) : An error occurred: Channel is closed.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 155, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
  File "C:\Python\Lib\site-packages\pika\adapters\blocking_connection.py", line 2259, in basic_publish
    self._impl.basic_publish(
  File "C:\Python\Lib\site-packages\pika\channel.py", line 423, in basic_publish
    self._raise_if_not_open()
  File "C:\Python\Lib\site-packages\pika\channel.py", line 1403, in _raise_if_not_open
    raise exceptions.ChannelWrongStateError('Channel is closed.')
pika.exceptions.ChannelWrongStateError: Channel is closed.
2024-02-20 15:55:21,726 INFO __main__ Thread-3 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 15:55:21,780 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 15:55:25,126 INFO __main__ Thread-4 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 16:01:14,525 WARNING __main__ Thread-8 (process_request_thread) : No  news data found.
2024-02-20 16:01:18,517 INFO __main__ Thread-9 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 16:02:42,358 WARNING __main__ Thread-3 (process_request_thread) : No   news data found.
2024-02-20 16:02:42,411 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:06:08,210 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:06:11,886 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:06:17,736 INFO __main__ Thread-5 (process_request_thread) : 123 news data published to RabbitMQ.
2024-02-20 16:06:49,315 INFO __main__ Thread-7 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:07:02,899 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:07:06,368 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:09:14,777 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:09:17,896 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:12:32,973 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:12:36,255 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:14:34,884 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:14:41,113 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:16:14,531 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:16:17,443 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:16:41,582 INFO __main__ Thread-7 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 16:19:03,584 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:19:08,420 INFO __main__ Thread-4 (process_request_thread) : 123 news data published to RabbitMQ.
2024-02-20 16:21:53,184 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 16:21:56,797 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:22:01,377 INFO __main__ Thread-5 (process_request_thread) :  John Deere news data published to RabbitMQ.
2024-02-20 16:22:12,777 INFO __main__ Thread-7 (process_request_thread) : Cummins news data published to RabbitMQ.
2024-02-20 16:33:48,790 ERROR app MainThread : Error fetching news for test: 'dict' object has no attribute 'entries'
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 85, in fetch_store_news
    for news in feed_data.entries[:MAX_RESULT]:
                ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'entries'
2024-02-20 16:33:48,934 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:33:49,993 INFO app MainThread : Cummins news data published to RabbitMQ.
2024-02-20 16:33:50,504 WARNING app MainThread : No InvalidKeyword123 news data found.
2024-02-20 16:38:50,907 ERROR app MainThread : Error fetching news for test: 'dict' object has no attribute 'entries'
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 85, in fetch_store_news
    for news in feed_data.entries[:MAX_RESULT]:
                ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'entries'
2024-02-20 16:43:10,259 ERROR app MainThread : Error fetching news for test: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 100, in fetch_store_news
    data_entry = CompetitorNews.query.filter_by(OEM=key).first()
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 23, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\sqlalchemy\orm\scoping.py", line 221, in __call__
    sess = self.registry()
           ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\sqlalchemy\util\_collections.py", line 638, in __call__
    key = self.scopefunc()
          ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask_sqlalchemy\session.py", line 111, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-02-20 16:46:22,330 ERROR app MainThread : Error fetching news for test: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 100, in fetch_store_news
    data_entry = CompetitorNews.query.filter_by(OEM=key).first()
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask_sqlalchemy\model.py", line 23, in __get__
    cls, session=cls.__fsa__.session()  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\sqlalchemy\orm\scoping.py", line 221, in __call__
    sess = self.registry()
           ^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\sqlalchemy\util\_collections.py", line 638, in __call__
    key = self.scopefunc()
          ^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\flask_sqlalchemy\session.py", line 111, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
2024-02-20 16:47:39,532 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:48:47,141 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:53:27,919 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:53:59,369 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:57:10,127 ERROR app MainThread : An error occurred: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    connection, channel = setup_rabbitmq()
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
2024-02-20 16:57:10,134 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:57:10,199 WARNING app MainThread : No invalid_keyword news data found.
2024-02-20 16:59:27,067 ERROR app MainThread : An error occurred: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 152, in user
    connection, channel = setup_rabbitmq()
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
2024-02-20 16:59:27,074 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 16:59:27,141 WARNING app MainThread : No invalid_keyword news data found.
2024-02-20 17:00:34,894 ERROR app MainThread : An error occurred: 'NoneType' object has no attribute 'basic_publish'
Traceback (most recent call last):
  File "C:\CSA\competitor-news\attempt\app.py", line 154, in user
    channel.basic_publish(exchange='my_exchange',routing_key='my_queue', body=json.dumps(news_data))
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'basic_publish'
2024-02-20 17:00:34,901 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 17:00:34,906 WARNING app MainThread : No invalid_keyword news data found.
2024-02-20 17:03:38,680 INFO app MainThread : test_keyword news data published to RabbitMQ.
2024-02-20 17:03:38,688 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 17:03:38,756 WARNING app MainThread : No invalid_keyword news data found.
2024-02-20 17:20:49,360 INFO app MainThread : RabbitMQ connection closed.
2024-02-20 17:21:00,991 INFO __main__ Thread-3 (process_request_thread) : RabbitMQ connection closed.
2024-02-20 17:21:04,477 INFO __main__ Thread-4 (process_request_thread) : Cummins news data published to RabbitMQ.
